name: Python Test Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip -y

      - name: Run Python Script
        run: python3 main.py

      - name: 24f3004165@ds.study.iitm.ac.in
        run: echo "GitHub Action Step with Email Name"
